app = "seu-app-laravel"
primary_region = "gru"  # Altere para sua região

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/database/database.sqlite"

[mounts]
  source = "laravel_data"
  destination = "/var/www/html/database"