name: Deploy to Oracle VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "cd /var/www && git pull origin main && \
        composer install --no-dev && \
        npm install && npm run build && \
        php artisan migrate --force && \
        php artisan optimize:clear"
