name: Deploy Laravel to Oracle VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Run Deploy Commands
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
          cd /var/www/html &&
          git pull origin main &&
          composer install --no-interaction --no-dev --optimize-autoloader &&
          npm install --omit=dev && # Alterado para --omit=dev
          npm install vite --global && # Instala o Vite globalmente
          npm run build &&
          php artisan optimize:clear
        "
