name: Deploy Laravel to Oracle VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run Deploy Commands
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            set -e # Exit immediately if any command fails
            cd /var/www/html
            
            # Update code
            git pull origin main
            
            # PHP dependencies
            composer install --no-interaction --no-dev --optimize-autoloader
            
            # Node dependencies and build
            sudo npm ci --omit=dev
            sudo npm install vite
            sudo npm run build
            
            # Laravel optimizations
            sudo php artisan optimize:clear
            sudo php artisan storage:link
            
            # Fix permissions
            sudo chown -R www-data:www-data storage bootstrap/cache public/build
            sudo chmod -R 775 storage bootstrap/cache
          EOF
