name: Test SSH Connection
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH Access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          script: echo "Conexão SSH funcionou!"
